name: Repo - get next SemVer
# description: get next SemVer. Action-Source: https://github.com/WyriHaximus/github-action-next-semvers
run-name: get next SemVer by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      Major:
        description: next SemVer is a Major
        type: boolean
        required: true
        default: false
      Minor:
        description: next SemVer is a Minor
        type: boolean
        required: true
        default: false
      Patch:
        description: next SemVer is a Patch
        type: boolean
        required: true
        default: false
  workflow_call:
    inputs:
      Major:
        description: next SemVer is a Mayor
        type: boolean
        required: true
        default: false
      Minor:
        description: next SemVer is a Minor
        type: boolean
        required: true
        default: false
      Patch:
        description: next SemVer is a Patch
        type: boolean
        required: true
        default: false

    outputs:
      prevtag:
        description: "previous SemVer"
        value: ${{ env.PREV_TAG_V }}
      vsemver:
        description: "the next v SemVer"
        value: ${{ env.RELEASE_TAG_V}}
      semver:
        description: "the next SemVer output"
        value: ${{ env.RELEASE_TAG }}

env:
  RELEASE_TAG: latest      # will be set later
  RELEASE_TAG_V: v0.0.0    # will be set later
  PREV_TAG_V: v0.0.0       # will be set later
  
jobs:
  generate-SemVer:
    runs-on: ubuntu-latest
    steps:
      - name: add Summary item
        run: |
          echo "***get next SemVer***" >> $GITHUB_STEP_SUMMARY
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: add Summary item
        run: |
          echo "- previous version: ${{ steps.previoustag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "PREV_TAG_V=${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV
        
      - name: "Get next version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Next possible tag
        shell: bash
        run: |
          echo "- MAJOR: ${{ steps.semvers.outputs.v_major }} | ${{ steps.semvers.outputs.major }}"
          echo "- MINOR: ${{ steps.semvers.outputs.v_minor }} | ${{ steps.semvers.outputs.minor }}"
          echo "- PATCH: ${{ steps.semvers.outputs.v_patch }} | ${{ steps.semvers.outputs.patch }}"

      - name: isMajor
        id: is-major
        if: ${{ inputs.Major == true }}
        run: |
          echo "- new version: ${{ steps.semvers.outputs.v_major }} | ${{ steps.semvers.outputs.major }}" >> $GITHUB_STEP_SUMMARY
          echo "RELEASE_TAG=${{ steps.semvers.outputs.major }}" >> $GITHUB_ENV
          echo "RELEASE_TAG_V=${{ steps.semvers.outputs.v_major }}" >> $GITHUB_ENV

      - name: isMinor
        id: is-minor
        if: ${{ inputs.Minor == true }}
        run: |
          echo "- new version: ${{ steps.semvers.outputs.v_minor }} | ${{ steps.semvers.outputs.minor }}" >> $GITHUB_STEP_SUMMARY
          echo "RELEASE_TAG=${{ steps.semvers.outputs.minor }}" >> $GITHUB_ENV
          echo "RELEASE_TAG_V=${{ steps.semvers.outputs.v_minor }}" >> $GITHUB_ENV

      - name: isPatch
        id: is-patch
        if: ${{ inputs.Patch == true }}
        run: |
          echo "- new version: ${{ steps.semvers.outputs.v_patch }} | ${{ steps.semvers.outputs.patch }}" >> $GITHUB_STEP_SUMMARY
          echo "RELEASE_TAG=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV
          echo "RELEASE_TAG_V=${{ steps.semvers.outputs.v_patch }}" >> $GITHUB_ENV

      - name: output
        run: |
          echo "RELEASE_TAG: ${{ env.RELEASE_TAG }}"
          echo "RELEASE_TAG=$(echo ${{ env.RELEASE_TAG }})" >> $GITHUB_OUTPUT
          echo "RELEASE_TAG_V=$(echo ${{ env.RELEASE_TAG_V }})" >> $GITHUB_OUTPUT
          echo "PREV_TAG_V=$(echo ${{ env.PREV_TAG_V }})" >> $GITHUB_OUTPUT


