name: call wf get next SemVer

on:
  workflow_dispatch:

jobs:
  job1:
    name: "Call other workflow"
    uses: Zheng-Bote/gha-next-semvers/.github/workflows/repo-get_next_version.yml@master
    with:
      Major: false
      Minor: true
      Patch: false
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: "Print my_var"
        run: |
          echo "prevtag: ${{needs.job1.outputs.prevtag}}"
          echo "vsemver: ${{needs.job1.outputs.vsemver}}"
          echo "semver: ${{needs.job1.outputs.semver}}"
